-- DROP MATERIALIZED VIEW IF EXISTS demographics CASCADE;
-- CREATE MATERIALIZED VIEW demographics AS

-- SELECT 
--     adm.subject_id,
--     adm.hadm_id,
--     adm.insurance,
--     adm.language,
--     adm.religion,
--     adm.marital_status,
--     adm.ethnicity,
--     adm.diagnosis
-- FROM admissions adm
-- LEFT JOIN 

-- -- LANGUAGE plpgsql;
             


-- -- Male
-- -- non-Hispanic black
-- -- Hispanic
-- -- Asian
-- -- Native
-- -- Other
-- -- Age25to29
-- -- Age30to34
-- -- Age35to39
-- -- Age40to44
-- -- Age45to49
-- -- Age50to54
-- -- Age55to59
-- -- Age60to64
-- -- Age65to69
-- -- Age70to74
-- -- Age75to79
-- -- Age 80 or older
-- -- Veteran
-- -- BMI>=30
-- -- Exercise
-- -- Daily smoker
-- -- Occasional smoker
-- -- Former smoker
-- -- Divorced
-- -- Widowed
-- -- Separated
-- -- Never marricu.d
-- -- Member of an Unmarricu.d couple 
-- -- Did not graduate from high school 
-- -- Graduated high school
-- -- Some college